#!/bin/bash

# I've noticed the first two uses of "beacon" after "kissattach"
# appends two garbage bytes onto the end of the packet before the
# termination flag.

beacon -c "SYSTEM" -d "RADIO" -s kdr1 "rspd 10000"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "tune 19680000"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "tfrq 441000000"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "tmod 5"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "tpwr 63"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "tdev 5000"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "rfrq 441000000"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "dmod 1"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "rdev 5000"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "tspd 10000"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "tscr 1"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "rscr 1"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "prec 20"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "prep x0000"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "dife 1"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "difd 1"
beacon -c "SYSTEM" -d "RADIO" -s kdr1 "aply"

