#!/bin/bash

# I've noticed the first two uses of "beacon" after "kissattach"
# appends two garbage bytes onto the end of the packet before the
# termination flag.

beacon -s kdr1 "tlnk 1"
beacon -s kdr1 "rlnk 1"
beacon -s kdr1 "rspd 1000"
beacon -s kdr1 "tune 19680000"
beacon -s kdr1 "tfrq 441000000"
beacon -s kdr1 "tmod 5"
beacon -s kdr1 "tpwr 63"
beacon -s kdr1 "tdev 2000"
beacon -s kdr1 "rfrq 441000000"
beacon -s kdr1 "dmod 1"
beacon -s kdr1 "rdev 2000"
beacon -s kdr1 "tspd 1000"
beacon -s kdr1 "tscr 1"
beacon -s kdr1 "rscr 1"
beacon -s kdr1 "prec 16"
beacon -s kdr1 "prep x0000"
beacon -s kdr1 "dife 1"
beacon -s kdr1 "difd 1"
beacon -s kdr1 "ifbw 2"
beacon -s kdr1 "aply"
beacon -s kdr1 "rvit 1"
beacon -s kdr1 "tcnv 1"
