#!/bin/bash
# Retrieve and install programs to use with digital radio.
apt-get update
apt-get upgrade
apt-get install socat ax25-tools openjdk-7-jre librxtx-java unzip
mkdir ~/YAAC
wget www.ka2ddo.org/ka2ddo/YAAC.zip
unzip YYAC.zip -d ~/YAAC
./get-aprx
